mainSections:
  - blog
  - posts
  - news

# titleSeparator: '|' # Title separator. Default to -.

description: Software Engineer & Technical Writer
keywords: Blogger, Developer, JavaScript, React JS, Node JS, Php, SQL, NoSQL, GoLang, Python
# images:
#   - site-feature-image.jpg

# metaRobots: noindex, nofollow # Default value for Meta Tag robots
# metaRobots:  # disable Meta Tag robots

# logo: images/home.svg # Logo image. Default to images/logo.png.
logo: false # Disable Logo
brand: "Vipin Kumar Madhaan"

palette: blue # Default palette. Optional. You'll need to clear the browser cache after modifying this.
# Available palettes. Default to ALL. Empty array means disable.
# palettes:
#  - blue
#  - blue-gray
#  - brown
#  - cyan
#  - green
#  - indigo
#  - orange
#  - pink
#  - purple
#  - red
#  - teal
#  - yellow

color: light # light, dark or auto. Default to auto.

# fullWidth: true # Full width.
# fixedHeader: false # Turn on/off fixed header.

dateFormat: ":date_long"

# Google Adsense
googleAdsense: 

# math: true # Enable math globally.
toc: false # Disable TOC globally.
# tocPosition: content
# breadcrumb: false # Disable breadcrumb
# breadcrumbDivider: > # Breadcrumb divider
# diagram: true
# socialShare: false # disable social network sharing
# searchBar: false # disable search-bar

poweredBy: false # Whether to show powered by.

# readingTime: false # Whether to display the reading time.
# postDate: false # Whether to display the post date in the post meta section.

# featuredPostCount: 10 # The number of featured posts shown in sidebar. Turn off by setting it to false.
# recentPostCount: 10 # The number of recent posts shown in sidebar. Turn off by setting it to false.
# relatedPostCount: 10 # The number of related posts. Turn off by setting it to false.
# categoryCount: 10 # The number of categories shown in sidebar. Turn off by setting it to false.
# tagCount: 10 # The number of tags shown in sidebar. Turn off by setting it to false.
# seriesCount: 20 # The number of series shown in sidebar. Turn off by setting it to false.
# taxonomyPaginate: 5 # Default to 10.
taxonomyPostCount: 20 # The number of taxonomy's posts. Turn off by setting it to false.
countTaxonomyPosts: true # Count posts of taxonomy.

# sidebarTaxonomies: [categories, tags, series] # The order of taxonomies on the sidebar.

# pinnedPost: false # Turn on/off pinned posts.
pinnedPostCount: 3 # The number of pinned posts.

# Custom CSS and JS
customCSS:
customJS:

tocWordCount: 1 # TOC is displayed only if the post's word count exceeds this value.

titleCase: true # Capitalized title.

viewer: true # Image Viewer

# backgroundImage: ['/images/bg-light.png', '/images/bg-dark.png']
# rss: home # link the RSS button to homepage all the times.

sidebar:
  # fixed: true
  # archives: true # Enable archives widget
  # taxonomiesToggle: false # Disable taxonomy toggle
  taxonomiesToggleArchives: false
  # categories: true # Enable categories widget
  # tags: true # Enable tags widget
  # series: true # Enable series widget
  # authors: true # Enable authors widget
  # postsToggle: false # Disable posts toggle
  # featuredPosts: true # Enable featured posts widget
  # recentPosts: true # Enable featured posts widget
  # collapsed: true # Collapse sidebar widgets by default on small screens.

codeBlock:
  maxLines: 25
  lineNos: false # true/false represents that show/hide the line numbers by default.

post:
  excerpt: ''
  excerptMaxLength: 215
  copyright: false # Whether to display copyright section on each post.
  # plainifyExcerpt: false # Format excerpt in HTML if false.
  featuredImage: true # Show the featured image above the content.
  numberifyHeadings: true # Count headings automatically.
  # numberifyHeadingsEndLevel: 4 # The depth of headings to count. Default to 6.
  numberifyHeadingsSeparator: . # The separator between of number and headings.
  # tocStyleType: decimal # The TOC's CSS list-style-type property.
  # imageTitleAsCaption: true
  panel: false # Disable the post panel.
  # nav: false # Disable post navigations.
  # The page position after clicking the read more button, read more from content if true. Default to the beginning of page.
  # It supports only of the manual summaries spliting via <!--more-->.
  # readMoreFromContent: true

archive:
  paginate: 20 # Archive pagination. Default to 100.
  # basePath = "/archive" # The base path of archive pages.
  # dateFormat: 01-02 # Archive date format. Default to Jan 2.

analytics:
  # baidu:  # Baidu Analytics

# Site verification
siteVerification:
  google: "Iv7Ykyoy37qO1y8uh_uz8MXCk5a6pH31QUg0_5kqNmM"
  bing: "883A41EABD86043CA9E5B963D526D641"
  yandex: "1f990bf33192771e"
  baidu: 
  baiduUnion:  # Baidu Union
  so: 
  sogou: 
  shenma: 
  pinterest: "6cab42d499d5ef9f66cfddcb293a7775"
  followit: # "dcC8BZLtJWjSqSKMfDQA"

creativeCommons:
  # by: true # Credit must be given to you, the creator.
  # nc: true # Only noncommercial use of your work is permitted.
  # nd: true # No derivatives or adaptations of your work are permitted.
  # sa: true # Adaptations must be shared under the same terms.

# utterances:
  # repo: myblog # Replace with your repository.
  #issueTerm: pathname # pathname, url, title, og:title
  # label: comment
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  #theme:  

#staticman:
  #endpoint: https://yourstaticmaninstance # Required, replace with your own Staticman instance.
  #repo: user/repo # Required
  #service: github # or gitlab. Default to GitHub.
  #branch: main # Default to master.
  #property: comments # Default to comments.
  #sorting: desc # Default to asc.
  #reCaptchaKey: "" # The reCaptcha site key.
  #reCaptchaSecret: "" # The reCaptcha encrypted secret. You'll need to encrypt plain secret via https://yourstaticmaninstance/v3/encrypt/PLAINSECRET.
  #extraFields: # Extra fields. Available fiedls: url.
  #  - url
  #requiredFields: # Extra required fields. Available fields: email and the extra fields.
  #  - email
  #  - url
  #paginate: 5 # Default to 10.
  #moderation: false # Same as Staticman's moderation.

# See https://giscus.app
giscus:
  repo: "VipinMadhaan/iVipin"
  repoId: "R_kgDOIJKaTQ"
  category: "General"
  categoryId: "DIC_kwDOLMZCOc4Cc6Ut"
  # theme: "dark" # Default to auto.
  mapping: "og:title" # Default to pathname.
  inputPosition: "bottom" # Default to top.
  # reactions: false # Disable reactions.
  # metadata: true # Emit discussion metadata.
  # lang: "en" # Specify language, default to site language.
  # lazyLoading: false # Default to true.
  # strict: true # strict mapping match default false

search:
  # paginate: 5 # Pagination. Default to 10.
  # resultContentWordCount: 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  fuse:
    # ignoreLocation: true
    # location: 0
    # isCaseSensitive: false
    minMatchCharLength: 3
    threshold: 0.1
    # distance: 100
    # useExtendedSearch: true

# docsearch:
  # https://docsearch.algolia.com/docs/api
  # container: ".search-bar" # replace it if necessary, default to '.search-bar'.
  # appId: ""
  # apiKey: ""
  # indexName: ""
  # debug: true

# algolia:
#   appId: "K8FA9ZQS00"
#   apiKey: "4ac30f638afa728acd8e6eef8b6fd5a6"
#   indexName: "prod_ivipin"
#   paginate: 10
#   stallThreshold: 500

reward:
  # alipay: images/reward/alipay.png
  # wechat: images/reward/wechat.png
  paypal: images/reward/paypal.png
  patreon: images/reward/patreon.png
  # liberapay: images/reward/liberapay.png

#share:
  #addThis:  # AddThis pubid.

#actionsPanel:
  # disabled: true

# Comment or remove this settings to disable font size switcher.
# fontSize:
  # extraSmall: 1rem
  # small: 1.1rem
  # large: 1.3rem
  # extraLarge: 1.4rem

pwa:
  manifest:
    # name:  # Default to site title.
    short_name: iVipin
    # display: fullscreen # Default to standalone.
    # description:  # Default to site description.
    # theme_color: 
    # background_color: 

    # Icons
    # [[pwa.manifest.icons]]
    #   sizes: 96x96
    #   src: /images/icons/icon-96x96.png
    # [[pwa.manifest.icons]]
    #   sizes: 144x144
    #   src: /images/icons/icon-144x144.png

contact:
  # endpoint: https://formsubmit.io/send/Vipin.Madhaan@gmail.com # Backend endpoint, remove this line if you're using Netlify.
  # file: true # Enable file upload
  # fileField: image # The name of file field.
  # reCaptcha:
    # siteKey: ""

repo:
  url: https://github.com/VipinMadhaan/ivipin
  branch: main
  # subPath: exampleSite
  # dateFormat: 02/01/2006, 15:04:05 PM

topAppBar:
  social:
    twitter: VipinMadhaan
    linkedin: VipinMadhaan
    github: VipinMadhaan

#docs:
  # nav:
    # expand: true # Expand docs navigations.

#feeds:
  # content: true

social:
  twitter: VipinMadhaan
  linkedin: VipinMadhaan
  github: VipinMadhaan
  email: Vipin.Madhaan@gmail.com